In [2]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv("C:/Users/shrikishan soni/OneDrive/Desktop/spark internship/Iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [9]:
data.drop(["Species","Id"],axis="columns")

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [8]:
data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [12]:
from sklearn.cluster import KMeans
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [19]:
cls = KMeans(n_clusters = 2, )
cls.fit(data)

ValueError: could not convert string to float: 'Iris-virginica'

In [21]:
y_kmeans = cls.fit_predict(data)
cls.cluster_centers_

ValueError: could not convert string to float: 'Iris-virginica'

In [29]:
data['cluster']=  KMeans
data.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,cluster
0,1,5.1,3.5,1.4,0.2,Iris-setosa,<class 'sklearn.cluster._kmeans.KMeans'>
1,2,4.9,3.0,1.4,0.2,Iris-setosa,<class 'sklearn.cluster._kmeans.KMeans'>
2,3,4.7,3.2,1.3,0.2,Iris-setosa,<class 'sklearn.cluster._kmeans.KMeans'>
3,4,4.6,3.1,1.5,0.2,Iris-setosa,<class 'sklearn.cluster._kmeans.KMeans'>
4,5,5.0,3.6,1.4,0.2,Iris-setosa,<class 'sklearn.cluster._kmeans.KMeans'>

In [40]:
bestfeature=SelectKBest(score_func=chi2,k=5)

In [41]:
fit=bestfeature.fit(x,y)

In [42]:
datascores=pd.DataFrame(fit.scores_)
datacolumns=pd.DataFrame(x.columns)

In [43]:
featureScores=pd.concat([datacolumns,datascores],axis=1)
featureScores

               0            0
0             Id  3311.258278
1  SepalLengthCm    10.817821
2   SepalWidthCm     3.594499
3  PetalLengthCm   116.169847
4   PetalWidthCm    67.244828

In [44]:
featureScores.columns=["specs","score"]
sub_data=featureScores.nlargest(10,"score")
sub_data

           specs        score
0             Id  3311.258278
3  PetalLengthCm   116.169847
4   PetalWidthCm    67.244828
1  SepalLengthCm    10.817821
2   SepalWidthCm     3.594499

In [47]:
cols=sub_data.specs.to_list()
cols=cols+["Species"]

data1=data[cols]
data1

,Id,PetalLengthCm,PetalWidthCm,SepalLengthCm,SepalWidthCm,Species
0,1,1.4,0.2,5.1,3.5,Iris-setosa
1,2,1.4,0.2,4.9,3.0,Iris-setosa
2,3,1.3,0.2,4.7,3.2,Iris-setosa
3,4,1.5,0.2,4.6,3.1,Iris-setosa
4,5,1.4,0.2,5.0,3.6,Iris-setosa
...,...,...,...,...,...,...
145,146,5.2,2.3,6.7,3.0,Iris-virginica
146,147,5.0,1.9,6.3,2.5,Iris-virginica
147,148,5.2,2.0,6.5,3.0,Iris-virginica
148,149,5.4,2.3,6.2,3.4,Iris-virginica
149,150,5.1,1.8,5.9,3.0,Iris-virginica